 * CSV via python logging

   * linux issue?   <code> File "/home/martin/git_repos/TinkerForgeHelperLib/venv/lib/python3.12/site-packages/tinkerforge/ip_connection.py", line 844, in connect_unlocked
      tmp.connect((self.host, self.port))
        ConnectionRefusedError: [Errno 111] Connection refused'''
</code>
 * 
 * 